version: 0.0
os: linux
files:
    - source: test/index.html
      destination: /var/www/html/
    - source: scripts/elb/
      destination: /tmp/
permissions:
    - object: /var/www/html/index.html
      pattern: "**"
      mode: 775
      type:
        - file
hooks:
  ApplicationStop:
    - location: /tmp/deregister_from_elb.sh
    - location: /tmp/stop_httpd.sh
  ApplicationStart:
    - location: /tmp/start_httpd.sh
    - location: /tmp/register_with_elb.sh
