version: 0.0
os: linux
files:
    - source: test/index.html
      destination: /var/www/html/
permissions:
    - object: /var/www/html/index.html
      pattern: "**"
      mode: 775
      type:
        - file
#hooks:
#  ApplicationStop:
#    - location: scripts/elb/deregister_from_elb.sh
#    - location: scripts/elb/stop_httpd.sh
#  ApplicationStart:
#    - location: scripts/elb/start_httpd.sh
#    - location: scripts/elb/register_with_elb.sh
